# Indexes et slices

## Complément - niveau basique

In [1]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
plt.ion()

J'espère que vous êtes à présent convaincus qu'il est possible de faire énormément de choses avec numpy en faisant des opérations entre tableaux, et sans aller référencer un par un les éléments des tableaux.

Il est temps maintenant de voir que l'on peut *aussi* manipuler les tableaux numpy avec des indexes.

### Indexation par des entiers et tuples

La façon la plus naturelle d'utiliser un tableau, habituellement c'est à travers des indices. On peut aussi bien sûr accéder aux éléments d'un tableau numpy par des indices :

In [3]:
n = 5
a = np.arange(n*n).reshape( (n, n)); print(a)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


Avec un seul index on obtient naturellement une ligne

In [4]:
a[0]

array([0, 1, 2, 3, 4])

In [5]:
# qu'on peut a nouveau indexer
a[0][2]

2

In [6]:
# ou plus simplement indexer par un tuple
a[0, 2]

2

In [42]:
# Naturellement on peut affecter une case
# individuellement
a[0][1] = 101
a[0, 2] = 102
print(a)

[[  0 101 102   3   4]
 [  5   6   7   8   9]
 [ 10  11  12  13  14]
 [ 15  16  17  18  19]
 [ 20  21  22  23  24]]


In [7]:
# Ou toute une ligne
a[2] = np.arange(200, 205); print(a)

[[  0   1   2   3   4]
 [  5   6   7   8   9]
 [200 201 202 203 204]
 [ 15  16  17  18  19]
 [ 20  21  22  23  24]]


In [9]:
# et on on peut aussi changer 
# toute une ligne par broadcasting
a[4] = 400; a

array([[  0,   1,   2,   3,   4],
       [  5,   6,   7,   8,   9],
       [200, 201, 202, 203, 204],
       [ 15,  16,  17,  18,  19],
       [400, 400, 400, 400, 400]])

# Slicing

Grâce au slicing on peut aussi référencer toute une colonne :

In [30]:
n = 5
a = np.arange(n*n).reshape( (n, n)); print(a)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [31]:
a[:, 3]

array([ 3,  8, 13, 18, 23])

C'est un tableau à une dimension, mais vous pouvez tout de même modifier la colonne par une affectation :

In [32]:
a[:, 3] = range(300, 305); print(a)

[[  0   1   2 300   4]
 [  5   6   7 301   9]
 [ 10  11  12 302  14]
 [ 15  16  17 303  19]
 [ 20  21  22 304  24]]


ou, ici également bien sûr, par broadcasting :

In [33]:
# on affecte un scalaire à une colonne
a[:, 2] = 200; print(a)

[[  0   1 200 300   4]
 [  5   6 200 301   9]
 [ 10  11 200 302  14]
 [ 15  16 200 303  19]
 [ 20  21 200 304  24]]


In [34]:
# ou on ajoute un scalaire à une colonne 
a[:, 4] += 400; print(a)

[[  0   1 200 300 404]
 [  5   6 200 301 409]
 [ 10  11 200 302 414]
 [ 15  16 200 303 419]
 [ 20  21 200 304 424]]


Les slices peuvent prendre une forme générale :

In [50]:
b = np.arange(100).reshape(10, 10); print(b)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]


In [51]:
# toutes les lignes de rang 1, 4, 7
b[1::3]

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79]])

In [52]:
# toutes les colonnes de rang 1, 5, 9
b[:, 1::4]

array([[ 1,  5,  9],
       [11, 15, 19],
       [21, 25, 29],
       [31, 35, 39],
       [41, 45, 49],
       [51, 55, 59],
       [61, 65, 69],
       [71, 75, 79],
       [81, 85, 89],
       [91, 95, 99]])

In [53]:
b[:, 1::4] = 0; print(b)

[[ 0  0  2  3  4  0  6  7  8  0]
 [10  0 12 13 14  0 16 17 18  0]
 [20  0 22 23 24  0 26 27 28  0]
 [30  0 32 33 34  0 36 37 38  0]
 [40  0 42 43 44  0 46 47 48  0]
 [50  0 52 53 54  0 56 57 58  0]
 [60  0 62 63 64  0 66 67 68  0]
 [70  0 72 73 74  0 76 77 78  0]
 [80  0 82 83 84  0 86 87 88  0]
 [90  0 92 93 94  0 96 97 98  0]]


Le slicing peut servir à extraire des blocs compacts:

In [55]:
# un bloc au hasard dans b
print(b[2:5, 6:9])

[[26 27 28]
 [36 37 38]
 [46 47 48]]


### `newaxis`

On peut utiliser également le symbole spécial `np.newaxis` en conjonstion avec un slice pour décaler les dimensions :

In [71]:
X = np.arange(1, 7); print(X)

[1 2 3 4 5 6]


In [72]:
X.shape

(6,)

In [73]:
Y = X[:, np.newaxis]; print(Y)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [74]:
Y.shape

(6, 1)

Et ainsi de suite :

In [75]:
Z = Y[:, np.newaxis]; Z

array([[[1]],

       [[2]],

       [[3]],

       [[4]],

       [[5]],

       [[6]]])

In [76]:
Z.shape

(6, 1, 1)

De cett façon par exemple, en combinant le slicing pour créer X et Y, et le broadcasting pour créer leur somme,  je peux créer facilement la table de tous les tirages de 2 dés à 6 faces :

In [80]:
dice = X + Y; dice

array([[ 2,  3,  4,  5,  6,  7],
       [ 3,  4,  5,  6,  7,  8],
       [ 4,  5,  6,  7,  8,  9],
       [ 5,  6,  7,  8,  9, 10],
       [ 6,  7,  8,  9, 10, 11],
       [ 7,  8,  9, 10, 11, 12]])

### Conclusion

Avec l'indexation et le slicing, on peut créer des tableaux qui sont des vues sur des fragments d'un tableau; on peut également déformer leur dimension grâce à `newaxis`; on peut modifier ces fragments, en utilisant un scalaire, un tableau, ou ne slice sur un autre tableau; les possibilités sont infinies.

In [81]:
b

array([[ 0,  0,  2,  3,  4,  0,  6,  7,  8,  0],
       [10,  0, 12, 13, 14,  0, 16, 17, 18,  0],
       [20,  0, 22, 23, 24,  0, 26, 27, 28,  0],
       [30,  0, 32, 33, 34,  0, 36, 37, 38,  0],
       [40,  0, 42, 43, 44,  0, 46, 47, 48,  0],
       [50,  0, 52, 53, 54,  0, 56, 57, 58,  0],
       [60,  0, 62, 63, 64,  0, 66, 67, 68,  0],
       [70,  0, 72, 73, 74,  0, 76, 77, 78,  0],
       [80,  0, 82, 83, 84,  0, 86, 87, 88,  0],
       [90,  0, 92, 93, 94,  0, 96, 97, 98,  0]])

In [82]:
dice

array([[ 2,  3,  4,  5,  6,  7],
       [ 3,  4,  5,  6,  7,  8],
       [ 4,  5,  6,  7,  8,  9],
       [ 5,  6,  7,  8,  9, 10],
       [ 6,  7,  8,  9, 10, 11],
       [ 7,  8,  9, 10, 11, 12]])

In [87]:
# les lignes de rangs 1, 3, 5
b[1:6:2]

array([[10,  0, 12, 13, 14,  0, 16, 17, 18,  0],
       [30,  0, 32, 33, 34,  0, 36, 37, 38,  0],
       [50,  0, 52, 53, 54,  0, 56, 57, 58,  0]])

In [86]:
# parmi ces lignes, les colonnes de rangs 1, 4, 7
b[1:6:2, 1::4]

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [92]:
# je peux affecter ce tableau (en fait cette vue) à par exemple un scalaire
b[1:6:2, 1::4] = 333

In [93]:
b

array([[  0,   0,   2,   3,   4,   0,   6,   7,   8,   0],
       [ 10, 333,  12,  13,  14, 333,  16,  17,  18, 333],
       [ 20,   0,  22,  23,  24,   0,  26,  27,  28,   0],
       [ 30, 333,  32,  33,  34, 333,  36,  37,  38, 333],
       [ 40,   0,  42,  43,  44,   0,  46,  47,  48,   0],
       [ 50, 333,  52,  53,  54, 333,  56,  57,  58, 333],
       [ 60,   0,  62,  63,  64,   0,  66,  67,  68,   0],
       [ 70,   0,  72,  73,  74,   0,  76,  77,  78,   0],
       [ 80,   0,  82,  83,  84,   0,  86,  87,  88,   0],
       [ 90,   0,  92,  93,  94,   0,  96,  97,  98,   0]])